# Generated by Django 5.2.7 on 2025-10-14 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula_ruc', models.CharField(help_text='Número de cédula única', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener 10 o 13 dígitos', regex='^\\d{10}$|^\\d{13}$')], verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido de 10 dígitos', regex='^\\d{10}$')])),
                ('cuenta_bancaria', models.CharField(blank=True, help_text='Número de cuenta para pagos', max_length=50, null=True, verbose_name='Número de cuenta bancaria')),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco', max_length=100, null=True, verbose_name='Banco')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
