# Generated by Django 5.2.7 on 2026-01-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
    ]
