# Generated by Django 5.2.7 on 2025-11-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_remove_cliente_etiqueta_cliente'),
        ('servicio_adicional', '0003_rename_cleinte_servicioadicional_cliente'),
        ('trabajos', '0007_delete_tiposervicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('TRABAJO', 'Trabajo'), ('SERVICIO', 'Servicio adicional')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='clientes.cliente')),
                ('servicio_adicional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='servicio_adicional.servicioadicional')),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='trabajos.trabajo')),
            ],
        ),
    ]
