# Generated by Django 5.2.7 on 2026-01-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0001_initial'),
        ('servicio_adicional', '0004_rename_activo_tiposervicio_estado'),
        ('trabajos', '0010_remove_trabajo_estado_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacobrar',
            name='saldo_pendiente',
        ),
        migrations.RemoveField(
            model_name='cuentacobrar',
            name='tipo_cuenta',
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='servicio_adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='servicio_adicional.servicioadicional'),
        ),
        migrations.AlterField(
            model_name='cuentacobrar',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='trabajos.trabajo'),
        ),
    ]
