# Generated by Django 5.2.7 on 2026-01-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0002_remove_cuentacobrar_saldo_pendiente_and_more'),
        ('trabajos', '0012_remove_trabajo_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobrar',
            name='trabajo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta', to='trabajos.trabajo'),
        ),
    ]
