# Generated by Django 5.2.7 on 2026-01-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0003_alter_cuentacobrar_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacobrar',
            name='tipo_cuenta',
            field=models.CharField(choices=[('TRABAJO', 'Trabajo'), ('SERVICIO', 'Servicio adicional')], default='TRABAJO', max_length=20),
        ),
    ]
