# Generated by Django 5.2.7 on 2026-01-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0004_cuentacobrar_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobrar',
            name='tipo_cuenta',
            field=models.CharField(choices=[('TRABAJO', 'Trabajo'), ('SERVICIO', 'Servicio adicional')], editable=False, max_length=20),
        ),
    ]
