# Generated by Django 5.2.7 on 2026-01-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0005_alter_cuentacobrar_tipo_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacobrar',
            name='estado',
        ),
    ]
