# Generated by Django 5.2.7 on 2025-11-06 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombres del cliente', max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=100)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CEDULA', 'Cédula'), ('RUC', 'Ruc'), ('PASAPORTE', 'Pasaporte')], max_length=20, null=True)),
                ('identificacion', models.CharField(blank=True, help_text='Número de identificación', max_length=20, null=True, unique=True)),
                ('etiqueta_cliente', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('PROPIETARIO', 'Propietario'), ('CONTACTO', 'Contacto')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^\\+?1?\\d{9,15}$')])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o notas adicionales')),
                ('estado', models.BooleanField(db_index=True, default=True, help_text='Indica si la persona está activa en el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
