# Generated by Django 5.2.7 on 2025-11-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='etiqueta_cliente',
        ),
    ]
