# Generated by Django 5.2.7 on 2026-01-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='numero_cheque',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='numero_recibo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
    ]
