# Generated by Django 5.2.7 on 2026-01-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cobrar', '0002_remove_cuentacobrar_saldo_pendiente_and_more'),
        ('pago', '0002_remove_pago_banco_remove_pago_numero_cheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cuenta_cobrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cuenta_cobrar.cuentacobrar'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
