# Generated by Django 5.2.7 on 2025-11-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajos', '0007_delete_tiposervicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('tipo_transaccion', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco')], max_length=20)),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.TextField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajos.formapago')),
            ],
        ),
    ]
