# Generated by Django 5.2.7 on 2026-01-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='tipo_transaccion',
        ),
    ]
