# Generated by Django 5.2.7 on 2026-01-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0003_remove_movimientocaja_referencia_and_more'),
        ('pago', '0003_alter_pago_cuenta_cobrar_alter_pago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='pago.pago'),
        ),
    ]
