# Generated by Django 5.2.7 on 2025-11-25 22:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_etiqueta_cliente'),
        ('servicio_adicional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicio', models.CharField(max_length=50, unique=True)),
                ('fecha_servicio', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_adicionales', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'db_table': 'servicio_adicional',
                'ordering': ['-fecha_servicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicionalDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('servicio_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicio_adicional.servicioadicional')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_servicio', to='servicio_adicional.tiposervicio')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio',
                'verbose_name_plural': 'Detalles de Servicios',
                'db_table': 'servicio_adicional_detalle',
                'ordering': ['id'],
            },
        ),
    ]
