# Generated by Django 5.2.7 on 2025-11-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_adicional', '0002_servicioadicional_servicioadicionaldetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicioadicional',
            old_name='cleinte',
            new_name='cliente',
        ),
    ]
