# Generated by Django 5.2.7 on 2026-01-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_adicional', '0003_rename_cleinte_servicioadicional_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='activo',
            new_name='estado',
        ),
    ]
