# Generated by Django 5.2.7 on 2025-10-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadotrabajo',
            options={'verbose_name': 'Estado de trabajo', 'verbose_name_plural': 'Estados de trabajo'},
        ),
        migrations.RemoveField(
            model_name='estadotrabajo',
            name='orden_secuencia',
        ),
    ]
