# Generated by Django 5.2.7 on 2025-10-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_alter_estadotrabajo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Trabajo Cancelado (no se culminó)')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='TrabajoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_relacionadas', to='trabajos.trabajo')),
            ],
            options={
                'verbose_name': 'Relación Trabajo-Persona',
                'verbose_name_plural': 'Relaciones Trabajo-Persona',
                'ordering': ['-created_at'],
            },
        ),
    ]
