# Generated by Django 5.2.7 on 2025-11-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_etiqueta_cliente'),
        ('trabajos', '0004_trabajo_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_etiqueta', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('PROPIETARIO', 'Propietario'), ('CONTACTO', 'Contacto')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_relacionados', to='clientes.cliente')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_relacionadas', to='trabajos.trabajo')),
            ],
            options={
                'verbose_name': 'Relación Trabajo-Persona',
                'verbose_name_plural': 'Relaciones Trabajo-Persona',
                'ordering': ['-created_at'],
                'unique_together': {('trabajo', 'cliente', 'tipo_etiqueta')},
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='cliente',
            field=models.ManyToManyField(related_name='trabajos', through='trabajos.TrabajoCliente', to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='TrabajoPersona',
        ),
    ]
