# Generated by Django 5.2.7 on 2025-11-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0005_trabajocliente_trabajo_cliente_delete_trabajopersona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='referencia_ubicacion',
        ),
        migrations.AlterField(
            model_name='trabajoestadohistorial',
            name='estado_trabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trabajos.estadotrabajo'),
        ),
    ]
