# Generated by Django 5.2.7 on 2025-11-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0006_remove_trabajo_prioridad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
