# Generated by Django 5.2.7 on 2026-01-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0007_delete_tiposervicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipotrabajo',
            old_name='activo',
            new_name='estado',
        ),
    ]
