# Generated by Django 5.2.7 on 2026-01-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0008_rename_activo_tipotrabajo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapago',
            old_name='activo',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='activo',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='trabajoestadohistorial',
            name='documentos_requeridos',
        ),
    ]
