# Generated by Django 5.2.7 on 2026-01-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0009_rename_activo_formapago_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='saldo_pendiente',
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
