# Generated by Django 5.2.7 on 2026-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0010_remove_trabajo_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Trabajo Cancelado (no se culminó)')], default='PENDIENTE', max_length=20),
        ),
    ]
