# Generated by Django 5.2.7 on 2026-01-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0011_trabajo_estado_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='estado_pago',
        ),
    ]
