# Generated by Django 5.2.7 on 2026-01-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_rename_fecha_creacion_empleado_created_at_and_more'),
        ('trabajos', '0013_remove_formapago_requiere_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rol', models.CharField(choices=[('TOPOGRAFO', 'Topógrafo'), ('Cadenero', 'Cadenero')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='empleados.empleado')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='trabajos.trabajo')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('trabajo', 'empleado', 'fecha', 'rol')},
            },
        ),
    ]
