# Generated by Django 5.2.7 on 2026-01-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0014_asignaciontrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontrabajo',
            name='rol',
            field=models.CharField(choices=[(1, 'Topógrafo'), (2, 'Cadenero')], max_length=20),
        ),
    ]
