# Generated by Django 5.2.7 on 2026-01-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0015_alter_asignaciontrabajo_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontrabajo',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Topógrafo'), (2, 'Cadenero')]),
        ),
    ]
