# Generated by Django 5.2.7 on 2026-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0016_alter_asignaciontrabajo_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(1, 'Topógrafo'), (2, 'Cadenero'), (3, 'Solo Carrera')], unique=True)),
                ('tarifa_dia', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tarifa por Rol',
                'verbose_name_plural': 'Tarifas por Rol',
            },
        ),
        migrations.AddField(
            model_name='asignaciontrabajo',
            name='adelanto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='asignaciontrabajo',
            name='carrera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='asignaciontrabajo',
            name='costo_personal_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='asignaciontrabajo',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='asignaciontrabajo',
            name='personal_adicional_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciontrabajo',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Topógrafo'), (2, 'Cadenero'), (3, 'Solo Carrera')]),
        ),
    ]
